######################################################################
# Automatically generated by qmake (2.01a) ??? ?? 22 16:59:06 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
CONFIG += console
# Input
QMAKE_CXXFLAGS += -I../ 
HEADERS += ../fxeditor.h
SOURCES += ../fxeditor.cpp main.cpp
